@host = https://localhost
@port = 7059
@token = CfDJ8Lz_EizIg3JIkV6SV7p4wuimp03T8d9ltb3sYLTI6AjNZZO0U6kb9T3_RzNOOqCV8SCyKd_S75vP1dGWXQL0plVp8OItXGPQz7wfO27al6muDOVrnW2PQDSitt6sc3aRPNkHDewLb7qE3RzIG1eGgUbTbsWL6ra4UiEXpfXFM4pyzG4sD8ROe22SVKG7eWMeAwUBHdCttms84p4akJHYDfYHh_jLAvplagAEXtJ10VUsXLPBAA3Gk3QDAeK_HnNFEgpYpErsgvi-t1OJpmBi9VnonbpSY3uBKbzHcIHDiYzpZpgY-rZHCMynL9t1UQZN9MqggSJ8JdYTLOk5CLkKcfKKo2KA90P_43QIfRIFj8BlYysWlZZ8u_yj6sYPkcyeMgs9qDEX1ij2PbtysmP3vGkP5yH1rvs-Sdsh0Mr8NglnvaP9YKSL1HK90bLkg54Dw0pNnEk7gg2sJ5aznNZWfxASjpoBXJjDUAt_l9qVzyBXRy3U22_moyCcFMjh4gI4-K0JRcqPmQWvoTwosT7IhIS3lV15edaR8AmZD42EF-IoBzQtXMfXSrfC3JjeTtiuxxRMG9uHxp1oAgvTPxR9_Q44pe22ITXZ-So4GexcOaoQ9tmFBfVa3QYEJ_z0_1WPlxX5MF3znPD2817NQnA0OffZRQPmqvLcbfmeyHBLH6lQAXOX54uycJ_JGsAkEzD7yRhTDUUfzy8q_aAeL-W3B1LsP0a2n__YVy-bD0Sb-N9Y4lADIOkniy3gNaQ5_UKZs2DvMbkpE8co6i_3LvbYe5-QuNysvUxg2Dx_C567gg8L

@Restaurants.API_HostAddress = https://localhost:7059


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###



POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Spicy Delights 3",
  "Description": "A culinary exerience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "22-333"
}

###



DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
  "Name": "Spicy Jet 1234",
  "Description": "A culinary exerience like no other 1234",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes
Content-Type: application/json

{
  "Name": "Spagheti Sertigonees 2",
  "Description": "Classic Spanish pasta dish with rich meat sauce",
  "Price": 16.99,
  "KiloCalories": 650
}

###



GET {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes/5

###



DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner@test.com",
  "password": "M@d@com786"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "yousuf.abbas@hotmail.com",
  "password": "M@d@com786"
}
