@host = https://localhost
@port = 7059
@token = CfDJ8Lz_EizIg3JIkV6SV7p4wuhE4V5eimyc7M60HvsV2XKfCWstPGJMjMKCJVpITw-IxxpwV8QPRb4JTEFoSfEaOXsQ3n0jf5azBS0uf0dD8lMbcXtxXr8Ye7UVaRmhe_IpaXL4uaT97c14U869NttQvtQEfPblCMvkoMK2s8W6mNXdvfEc_jRMywHEZPKJ8tgPoQTyhSHe6zkBFm3FdVdGV_o_RQmtMIzsnmNc0vNVhLDjG_15nbUCHqLKO9sxegK1aUJoMZN7SxhFsmF9qmc8BEk4J_SlZcOa0Y4_vcrVGC5hF2WPp7WiI7gA9R2cnRdEewfqRtIm5mJ_I9pQgg-2aNYlS2S3CXY-nyWySvxxeOpULK1cGj227TNv5nj8ywub3XZiZaRWFD-LuI4UnFXWd8vsVPuNQPn7poJPpZG__8aIg4mUO6E4LJF8HlDGLuvA4hs8qW5zOFfTmAILwzk2nHdLpcGDPC9lJsyTRtQ72KF37LbueyFYiWj6xcmWh0MwZbRiyNwmNuWoCh_8w1Cp54Lg-7y29lxI7JVlFoiCsGsySL_hTGmGNP0uhcNrkCZ_c4UGh6wD_iX0wBmmzTMDaZm3dG3lrSU-RsPp6hpsCut02N4jXoSQt076B7ldKJcSU74w6fCvlX8NQgrndDLfabZcTP39JeBJJ2KlhF2K6s0yz8WdBejAqqRjvaDOqyC3ETVv4L1VKFOxa196Q503KWQKOTSXEnuYCC68jerJBdrcfoFpFjzCrMt-KYvKTgUMzLdYlVe7PXQzEfOFGqd5J0R1WSMlGXEtaefPMtJ-wJCb0sCotvdoWTkIv3ZO5V5CiePZFTQChbZlWNxvn5nMqN4qMFDJbjmSoKObAzbkaJGXClzIYlHjk2c7r1maGHxVOtNCGkTqBzPwJiLJ7OswuTg

@Restaurants.API_HostAddress = https://localhost:7059


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###



POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Spicy Delights 4",
  "Description": "A culinary exerience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "22-333"
}

###



DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3

###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "updated name Spicy Delights 3",
  "Description": "updated A culinary exerience like no other deights 3",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes
Content-Type: application/json

{
  "Name": "Spagheti Sertigonees 2",
  "Description": "Classic Spanish pasta dish with rich meat sauce",
  "Price": 16.99,
  "KiloCalories": 650
}

###



GET {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes/5

###



DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner@test.com",
  "password": "M@d@com786"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "user@test.com",
  "password": "M@d@com786"
}
